name: "Liferay Build"
description: ""
author: "lgdd"

branding:
  icon: "loader"
  color: "blue"

inputs:
  build-tool:
    description: >
      Tool ("gradle" or "maven") to use to build the workspace.
    required: true
    default: "gradle"
  java-version:
    description: >
      Java version (default: '11')
      Check Liferay compatibility matrix: https://www.liferay.com/compatibility-matrix.
    required: true
    default: "11"
  java-distribution:
    description: >
      Java distribution (default: 'zulu')
      List of supported distributions for the setup-java action: https://github.com/actions/setup-java#supported-distributions
      Also check Liferay compatibility matrix: https://www.liferay.com/compatibility-matrix
    required: true
    default: "zulu"
  workspace-directory:
    description: >
      Path to your workspace if different from root directory.
      It will be use in this actions steps for the 'working-directory' directive.
    required: false
    default: .

runs:
  using: composite
  steps:
    - run: cp ${{ github.action_path }}/bin/go-build . && chmod +x go-build
      shell: bash
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: "gradle"
    - name: Set up Blade
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/liferay/liferay-blade-cli/master/cli/installers/local | bash
        echo "/home/runner/jpm/bin" >> $GITHUB_PATH
    - name: Build Workspace
      shell: bash
      working-directory: ${{ inputs.workspace-directory }}
      run: |
        ./go-build
